const sdata = [
    {
        id: 1,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 2,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 3,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 4,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 5,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 6,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 7,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 8,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 9,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 10,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 11,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 12,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 13,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 14,
        sname: "DARK",
        imgsrc: "https://shorturl.at/ghIM9",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80100172",
    },
    {
        id: 15,
        sname: "Stranger Things",
        imgsrc: "https://shorturl.at/brCI6",
        title: "A netflix original series",
        serlink: "https://www.netflix.com/in/title/80057281",
    },
    {
        id: 16,
        sname: "Vampire Diaries",
        imgsrc: "https://oyster.ignimgs.com/mediawiki/apis.ign.com/vampire-diaries/0/05/Tvdseason2.jpg",
        title: "Amazon prime original series",
        serlink: "https://shorturl.at/psNY1",
    },
]

export default sdata;